### ISSUE TITLE
Titel zu lang

### ISSUE THREAD

**Issue by apollo7321** [cwansart/voc_trainer#1]
Die Titelzeilen sind teilweise zu lang. Zum Beispiel wird in der Sprachauswahl die Titelzeile abgeschnitten. Wir sollten kürzere Titel verwenden.

![issue-title](https://cloud.githubusercontent.com/assets/1969270/5948016/c65e7b36-a741-11e4-8aa2-f4a29ec709d3.png)

**Comment by ghost** [comment]
Hier müsste man mal teste, wie es auf einem mobilen Gerät aussieht. Die Elemente auf dem Endgerät werden meist kleiner dargestellt, z.B. Iphone retina-Display.

**Comment by apollo7321** [comment]
Ich habe hier einen Emulator mit einer Auflösung von 1280x720 genommen, also relativ hoch. Das wird auf einem mobilen Gerät wohl nicht besser sein.
