### ISSUE TITLE
Auswahl der Checkboxen

### ISSUE THREAD

**Issue by ghost** [cwansart/voc_trainer#11]
Wenn man z.B. auf der Seite "Karteiverwaltung" eine Sprache öffnet und Karteien markiert, die Sprache aber anschließend wieder schließt, bleiben die gewählten karteien markiert.
So kann man auch Karteien aus verschiedenen Sprachen gleichzeitig markieren.

TODO: Wenn eine Sprache geschlossen wird, müssen die checkboxen automatisch de-markiert werden.

**Comment by apollo7321** [comment]
Das dachte ich zuerst auch, aber die Funktionalität ist keiner Weise beeinträchtigt, da die Variable "aktuelleSprache" immer neu gesetzt wird, wenn eine der collapsibles geöffnet werden.

Es sei denn, du möchtest die gerne Auswahl entfernen, wenn die geschlossen werden. Das hatte ich bisher leider noch nicht hinbekommen. :disappointed:
