### ISSUE TITLE
Logo einbinden

### ISSUE THREAD

**Issue by apollo7321** [cwansart/voc_trainer#18]
https://gist.github.com/LinusU/7515016

**Comment by ghost** [comment]
kannst ja beim nächsten mal, wenn du die app erstellst einfach mal schauen, ob es geklappt hat :)

**Comment by apollo7321** [comment]
Man musste die noch entsprechend kopieren. Dazu kann man im "hooks"-Ordner ein Skript erstellen, dass die Datei entsprechend kopiert. Das habe ich gemacht. :) Hast du gut gemacht, sieht gut aus!
