### ISSUE TITLE
Einrückung Korrigieren

### ISSUE THREAD

**Issue by apollo7321** [cwansart/voc_trainer#22]
Da durch die Nutzung verschiedener Editoren verschiedene Einrückungen zustande kamen, sollten wir zum Schluss, vor Abgabe, die Einrückung in allen Dateien noch einmal korrigieren.

**Comment by ghost** [comment]
auf jeden Fall.
wir wollten den Code am Ende ja eh nochmal etwas schöner strukturieren.
einrückungen, kommentare, usw.

**Comment by apollo7321** [comment]
Fertig. https://github.com/cwansart/voc_trainer/commit/2709702b55e3086d17025cae5634c827ad0c7057
