### ISSUE TITLE
Erscheinen/ Ausblenden der Meldungen

### ISSUE THREAD

**Issue by ghost** [cwansart/voc_trainer#26]
Es kommt immernoch zu Bugs was die Bestätigungsmeldungen angeht.
Beispiel: Man legt eine Kartei an und geht über den zurück-button (im Header) zurück.Eine Meldung erscheint, die da nicht hingehört.
Das müssen wir unbedingt mal ordentlich durchtesten und debuggen.

**Comment by apollo7321** [comment]
Wird neu implementiert, siehe Issue #27
