### ISSUE TITLE
Mehrere Sprachen bei Checkboxen (#NeueKartei) auswählbar

### ISSUE THREAD

**Issue by apollo7321** [cwansart/voc_trainer#28]
Ich vermute einfach mal, weil wir nicht, wie in den Beispielen, einen namen drin haben. http://demos.jquerymobile.com/1.4.5/checkboxradio-radio/#&ui-state=dialog

Kann aber auch was anderes sein...
![issue-checkbox](https://cloud.githubusercontent.com/assets/1969270/6085252/79945d18-ae38-11e4-8a1e-6a4123b0db5a.png)

**Comment by ghost** [comment]
das WAR aber mal richtig!
und ich hatte auch nen namen angegeben, als ich das erstellt hab :)
vielleicht ist der irgendwann beim anpassen verschütt gegangen.

**Comment by apollo7321** [comment]
Ich hatte den namen mal entfernt, weil ich dachte, er sei überflüssig! :sweat_smile:  Müsste man man ausprobieren. :smile:

**Comment by ghost** [comment]
achso :D macht ja nichts. Das ist ja zum glück nur ein mini-issue. :)

**Comment by apollo7321** [comment]
Es lag tatsächlich am name-Attribut. Ich habe es mal wieder hinzugefügt... :sweat:
