### ISSUE TITLE
NavBar rutscht aus dem Fenster heraus.

### ISSUE THREAD

**Issue by apollo7321** [cwansart/voc_trainer#3]
Wie schon besprochen, ist die Navbar etwas über den unteren Bildschirmrand hinausgerutscht.

![issue-navbar](https://cloud.githubusercontent.com/assets/1969270/5948083/64107064-a742-11e4-8884-255cc6af9877.png)

**Comment by ghost** [comment]
Da kümmer ich mich heute Abend drum.

**Comment by apollo7321** [comment]
Gefixt durch https://github.com/cwansart/voc_trainer/commit/9322cdf172a3d07c9573b37fa3e1a99bb69d37c1
