### ISSUE TITLE
Dauer des Lernens

### ISSUE THREAD

**Issue by mkotzjan** [cwansart/voc_trainer#31]
Die Dauer des Lernens wird nicht korrekt zurückgestellt. Wenn ich einmal lerne und und 30 sec. brauche wird bei einem zweiten Lernen die Zeit nicht zurückgestellt sondern addiert. Außerdem wird die Zeit über eine Minute nichtmehr richtig dargestellt, die Darstellung wechselt die ganze Zeit.

**Comment by apollo7321** [comment]
Ich habe den Code mal umgeschrieben. Die Anzeige sollte nun passen. Kannst du mal auf dem Rechner den Code pullen und dann im Browser testen, ob es bei dir immer noch addiert wird? Ich kann den Fehler hier nicht nachvollziehen.
