### ISSUE TITLE
Lösungswort endet mit Leerzeichen

### ISSUE THREAD

**Issue by mkotzjan** [cwansart/voc_trainer#32]
Meine Tastatur setzt hinter vervollständigte Wörtr automatische in Leerzeichen. Bei Lösungen aus einem Wort schien das kein Problem zu sein, jedoch wurde "Guten morgen " als falsch und "Guten morgen" als richtig angezeigt.

**Comment by apollo7321** [comment]
Notiz: vorm Speichern, trim anwenden → http://www.w3schools.com/jsref/jsref_trim_string.asp

**Comment by mkotzjan** [comment]
Nur um das klarzustellen:

Ich meinte schon das ich "Guten morgen" gespeichert habe, nur beim lernen wurde dann "Guten morgen " eingetragen. Weiß nicht ob das verständlich ist ;)

**Comment by apollo7321** [comment]
Ach so. Dann müssen wir trim trotzdem einfach anwenden, nachdem auf "prüfen" geklickt wurde.
