### ISSUE TITLE
"kein Inhalt"-Ein/Ausblenden dynamischer machen

### ISSUE THREAD

**Issue by apollo7321** [cwansart/voc_trainer#7]
Aus der index.js:

```
$('#kartei-sprachen').children()[0].setAttribute('style', 'display:none;');
$('#kartei-sprachen').children()[1].setAttribute('style', 'display:block;');
```

ist mit children()[0] und 1 sehr undynaisch. Wir sollten es mit Klassen/IDs austauschen und entsprechend verstecken. Sicherlich wäre .hide() hier keine schlechte Variante.

**Comment by ghost** [comment]
erledigt.
