### ISSUE TITLE
Controlgroup - Felder nicht zusammenhängend

### ISSUE THREAD

**Issue by ghost** [cwansart/voc_trainer#8]
Auf der Seite "Vokabelverwaltung" werden die Felder der Vokabeln einzeln dargestellt.

**Comment by apollo7321** [comment]
Im Vergleich zur Karteiverwaltung, haben wir hier die controlgroup direkt in die index.html ( https://github.com/cwansart/voc_trainer/blob/master/www/index.html#L207) geschrieben. Vielleicht funktioniert es ja, wenn wir die controlgroup mit in die index.js packen... Ich schaue mal ob da was zu machen ist....

**Comment by apollo7321** [comment]
Jo, so klappt's. Musste noch nen wrapper div in die index.html einfügen. :smile:
