### ISSUE TITLE
„Sprache wählen“ wenn keine Sprache vorhanden ist

### ISSUE THREAD

**Issue by apollo7321** [cwansart/voc_trainer#9]
Wenn keine Sprache vorhanden ist, wird die Box „Sprache auswählen“ auf der Seite #NeueKartei dennoch angezeigt. Diese sollte ausgeblendet werden.

```
if($.isEmptyObject(sprachen)) {
  // ausblenden
}
```

Siehe: http://api.jquery.com/jQuery.isEmptyObject/

Und:
![issue-kartei-add-no-lang_](https://cloud.githubusercontent.com/assets/1969270/5989365/a1e46fa4-a985-11e4-82a7-0606b6819094.png)

**Comment by ghost** [comment]
Ich kümmer mich drum :)

**Comment by ghost** [comment]
gefixt.
